version: '3.0'

services:

  pulsar-server:
    command: bin/pulsar standalone
    image: apachepulsar/pulsar-all:2.8.1
    container_name: pulsar-server
    hostname: pulsar-server
    volumes:
      - ./target/custom-sink-connector-0.0.1.nar:/pulsar/connectors/custom-sink-connector-0.0.1.nar
    ports:
    - 8080:8080
    - 6650:6650
    networks:
    - custom-sink-connector
    healthcheck:
      interval: 10s
      retries: 20
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:8080/admin/v2/clusters/standalone

volumes:
  custom-sink-connector:
    driver: local

networks:
  custom-sink-connector:
    driver: bridge